#!/usr/bin/env python3
"""
Builds the Enchantments site data from scripts/enchantments.yml.
Writes site/assets/data/enchantments.json.

Usage: run from anywhere; paths are resolved relative to this script.
"""
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
SRC_PATH = SCRIPT_DIR / "enchantments.yml"
OUT_PATH = SCRIPT_DIR.parent / "site" / "assets" / "data" / "enchantments.json"

try:
    import yaml
except ImportError as exc:
    sys.exit("PyYAML is required: python -m pip install pyyaml")


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "_", text.strip().lower()).strip("_")


def main():
    with open(SRC_PATH, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    enchantments = []
    for key, e in (data.get("enchantments") or {}).items():
        enchantments.append({
            "key": key,
            "name": e.get("name", key),
            "category": e.get("category", "Universal"),
            "summary": e.get("summary", ""),
            "max_level": e.get("max_level", "I"),
            "incompatible": list(e.get("incompatible") or []),
            "primary": list(e.get("primary") or []),
            "secondary": list(e.get("secondary") or []),
            "weight": e.get("weight", 1),
        })

    order = ["Armor", "Bow", "Tool", "Fishing", "Weapon", "Universal"]
    enchantments.sort(key=lambda e: (order.index(e["category"]) if e["category"] in order else 99, e["name"].lower()))

    payload = {
        "generated": "Auto-generated by scripts/build_enchantments.py — do not edit.",
        "enchantments": enchantments,
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(payload, indent=1), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(enchantments)} enchantments)")


if __name__ == "__main__":
    main()
