#!/usr/bin/env python3
"""
Builds the Top-3 Combos site data.
A combo = 1 race + 3 classes (matches classes-count: 3).
Score = sum of all buff magnitudes - sum of all debuff magnitudes across entries.
Writes the top 3 combos to site/assets/data/combos.json.

Usage: run from anywhere; paths are resolved relative to this script.
"""
import itertools
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent

sys.path.insert(0, str(SCRIPT_DIR))
import build_data  # reuse STAT_LABELS / FLAT_STATS / INVERTED_STATS / stat_to_entry

RACES_PATH = SCRIPT_DIR.parent / "plugin" / "races.yml"
CLASSES_PATH = SCRIPT_DIR.parent / "plugin" / "classes.yml"
OUT_PATH = SCRIPT_DIR.parent / "site" / "assets" / "data" / "combos.json"

try:
    import yaml
except ImportError as exc:
    sys.exit("PyYAML is required: python -m pip install pyyaml")

GROUPS = {
    1: "Warrior", 2: "Specialist", 3: "Adept", 4: "Healer", 5: "Guardian",
    6: "Shadow", 7: "Warlord", 8: "Mystic", 9: "Artisan", 10: "Weaver",
}

# classes-count used to build each combo
CLASSES_COUNT = 3


def entry_score(data):
    total = 0.0
    for sk, sv in (data.get("stat_buffs") or {}).items():
        e = build_data.stat_to_entry(sk, sv)
        total += e["magnitude"] if e["kind"] == "buff" else -e["magnitude"]
    for sk, sv in (data.get("perk_rewards") or {}).items():
        e = build_data.stat_to_entry(sk, sv)
        total += e["magnitude"] if e["kind"] == "buff" else -e["magnitude"]
    return total


def best_combo_for_race(race_key, race_data, classes_by_group):
    """Pick the 3 highest-scoring classes, one per distinct group, for a race."""
    # Score each individual class independently, then pick the top class per group
    # for the 3 groups that maximize the combined total.
    scored_by_group = {}
    for g, clist in classes_by_group.items():
        ranked = sorted(clist, key=lambda c: entry_score(c[1]), reverse=True)
        if ranked:
            scored_by_group[g] = ranked

    best = None
    best_total = None
    for groups_tuple in itertools.combinations(sorted(scored_by_group.keys()), CLASSES_COUNT):
        picks = []
        total = entry_score(race_data)
        for g in groups_tuple:
            cl = scored_by_group[g][0]
            picks.append(cl)
            total += entry_score(cl[1])
        if best_total is None or total > best_total:
            best_total = total
            best = picks
    return best, best_total


def main():
    with open(RACES_PATH, encoding="utf-8") as f:
        races_yaml = yaml.safe_load(f)
    with open(CLASSES_PATH, encoding="utf-8") as f:
        classes_yaml = yaml.safe_load(f)

    races = list((races_yaml.get("races") or {}).items())
    classes = list((classes_yaml.get("classes") or {}).items())

    # index classes by group, skippable? no permission concept here, include all
    classes_by_group = {}
    for k, v in classes:
        g = v.get("group", 0)
        classes_by_group.setdefault(g, []).append((k, v))

    scored = []
    for race_key, race_data in races:
        best_classes, total = best_combo_for_race(race_key, race_data, classes_by_group)
        if best_classes is None or total is None:
            continue
        scored.append((total, race_key, race_data, best_classes))

    scored.sort(key=lambda t: t[0], reverse=True)
    top = scored[:3]

    combos = []
    for rank, (total, race_key, race_data, best_classes) in enumerate(top, start=1):
        combos.append({
            "rank": rank,
            "score": round(total, 1),
            "race": race_key,
            "race_name": build_data.strip_mc_codes(race_data.get("display_name", race_key)),
            "classes": [k for k, _ in best_classes],
            "class_names": [
                build_data.strip_mc_codes(v.get("display_name", k)) for k, v in best_classes
            ],
        })

    payload = {
        "generated": "Auto-generated by scripts/build_combos.py — do not edit.",
        "combos": combos,
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(payload, indent=1), encoding="utf-8")
    for c in combos:
        print(f"#{c['rank']} {c['race_name']} + {', '.join(c['class_names'])} = {c['score']}")


if __name__ == "__main__":
    main()
